title: "Crash Stop Chicago Blog"
description: Updates and blog stuff for crashstop.org/chicago
url: "https://blog.crashstop.org"
baseurl: ""
timezone: America/Chicago

permalink: /:year/:month/:day/:title/

markdown: kramdown

plugins:
  - jekyll-feed

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - serve
  - vendor/
